using System;

namespace ProsperAPIWrapper
{
    public class Listing
    {
        #region Experian Credit Variables

        #region ALE
        public int? ALE001 { get; set; }
        public int? ALE002 { get; set; }
        public int? ALE005 { get; set; }
        public int? ALE007 { get; set; }
        public int? ALE022 { get; set; }
        public int? ALE023 { get; set; }
        public int? ALE026 { get; set; }
        public int? ALE071 { get; set; }
        public int? ALE074 { get; set; }
        public int? ALE075 { get; set; }
        public int? ALE076 { get; set; }
        public int? ALE077 { get; set; }
        public int? ALE078 { get; set; }
        public int? ALE080 { get; set; }
        public int? ALE081 { get; set; }
        public int? ALE084 { get; set; }
        public int? ALE403 { get; set; }
        public int? ALE501 { get; set; }
        public int? ALE502 { get; set; }
        public int? ALE503 { get; set; }
        public int? ALE601 { get; set; }
        public int? ALE720 { get; set; }
        public int? ALE724 { get; set; }
        public int? ALE740 { get; set; }
        public int? ALE801 { get; set; }
        public int? ALE804 { get; set; }
        public int? ALE901 { get; set; }
        public int? ALE903 { get; set; }
        public int? ALE904 { get; set; }
        public int? ALE905 { get; set; }
        public int? ALE906 { get; set; }
        public int? ALE908 { get; set; }
        #endregion

        #region ALL
        public int? ALL001 { get; set; }
        public int? ALL002 { get; set; }
        public int? ALL003 { get; set; }
        public int? ALL005 { get; set; }
        public int? ALL006 { get; set; }
        public int? ALL007 { get; set; }
        public int? ALL010 { get; set; }
        public int? ALL021 { get; set; }
        public int? ALL022 { get; set; }
        public int? ALL023 { get; set; }
        public int? ALL024 { get; set; }
        public int? ALL026 { get; set; }
        public int? ALL051 { get; set; }
        public int? ALL052 { get; set; }
        public int? ALL062 { get; set; }
        public int? ALL064 { get; set; }
        public int? ALL067 { get; set; }
        public int? ALL071 { get; set; }
        public int? ALL074 { get; set; }
        public int? ALL075 { get; set; }
        public int? ALL076 { get; set; }
        public int? ALL077 { get; set; }
        public int? ALL078 { get; set; }
        public int? ALL080 { get; set; }
        public int? ALL081 { get; set; }
        public int? ALL082 { get; set; }
        public int? ALL084 { get; set; }
        public int? ALL085 { get; set; }
        public int? ALL086 { get; set; }
        public int? ALL090 { get; set; }
        public int? ALL091 { get; set; }
        public int? ALL092 { get; set; }
        public int? ALL101 { get; set; }
        public int? ALL102 { get; set; }
        public int? ALL103 { get; set; }
        public int? ALL104 { get; set; }
        public int? ALL105 { get; set; }
        public int? ALL106 { get; set; }
        public int? ALL107 { get; set; }
        public int? ALL108 { get; set; }
        public int? ALL109 { get; set; }
        public int? ALL110 { get; set; }
        public int? ALL111 { get; set; }
        public int? ALL112 { get; set; }
        public int? ALL113 { get; set; }
        public int? ALL114 { get; set; }
        public int? ALL115 { get; set; }
        public int? ALL116 { get; set; }
        public int? ALL117 { get; set; }
        public int? ALL118 { get; set; }
        public int? ALL119 { get; set; }
        public int? ALL121 { get; set; }
        public int? ALL122 { get; set; }
        public int? ALL123 { get; set; }
        public int? ALL124 { get; set; }
        public int? ALL125 { get; set; }
        public int? ALL126 { get; set; }
        public int? ALL127 { get; set; }
        public int? ALL128 { get; set; }
        public int? ALL129 { get; set; }
        public int? ALL130 { get; set; }
        public int? ALL131 { get; set; }
        public int? ALL134 { get; set; }
        public int? ALL136 { get; set; }
        public int? ALL141 { get; set; }
        public int? ALL142 { get; set; }
        public int? ALL143 { get; set; }
        public int? ALL144 { get; set; }
        public int? ALL145 { get; set; }
        public int? ALL146 { get; set; }
        public int? ALL151 { get; set; }
        public int? ALL152 { get; set; }
        public int? ALL153 { get; set; }
        public int? ALL155 { get; set; }
        public int? ALL156 { get; set; }
        public int? ALL201 { get; set; }
        public int? ALL202 { get; set; }
        public int? ALL207 { get; set; }
        public int? ALL208 { get; set; }
        public int? ALL301 { get; set; }
        public int? ALL403 { get; set; }
        public int? ALL501 { get; set; }
        public int? ALL502 { get; set; }
        public int? ALL503 { get; set; }
        public int? ALL504 { get; set; }
        public int? ALL505 { get; set; }
        public int? ALL524 { get; set; }
        public int? ALL601 { get; set; }
        public int? ALL602 { get; set; }
        public int? ALL701 { get; set; }
        public int? ALL702 { get; set; }
        public int? ALL703 { get; set; }
        public int? ALL720 { get; set; }
        public int? ALL724 { get; set; }
        public int? ALL740 { get; set; }
        public int? ALL760 { get; set; }
        public int? ALL780 { get; set; }
        public int? ALL790 { get; set; }
        public int? ALL801 { get; set; }
        public int? ALL803 { get; set; }
        public int? ALL804 { get; set; }
        public int? ALL805 { get; set; }
        public int? ALL806 { get; set; }
        public int? ALL807 { get; set; }
        public int? ALL901 { get; set; }
        public int? ALL903 { get; set; }
        public int? ALL904 { get; set; }
        public int? ALL905 { get; set; }
        public int? ALL906 { get; set; }
        public int? ALL907 { get; set; }
        
        #endregion

        #region AUT
        public int? AUT001 { get; set; }
        public int? AUT071 { get; set; }
        public int? AUT720 { get; set; }
        #endregion

        #region BAC
        public int? BAC001 { get; set; }
        public int? BAC002 { get; set; }
        public int? BAC005 { get; set; }
        public int? BAC007 { get; set; }
        public int? BAC022 { get; set; }
        public int? BAC023 { get; set; }
        public int? BAC026 { get; set; }
        public int? BAC028 { get; set; }
        public int? BAC031 { get; set; }
        public int? BAC035 { get; set; }
        public int? BAC037 { get; set; }
        public int? BAC042 { get; set; }
        public int? BAC044 { get; set; }
        public int? BAC045 { get; set; }
        public int? BAC071 { get; set; }
        public int? BAC074 { get; set; }
        public int? BAC075 { get; set; }
        public int? BAC076 { get; set; }
        public int? BAC077 { get; set; }
        public int? BAC078 { get; set; }
        public int? BAC080 { get; set; }
        public int? BAC081 { get; set; }
        public int? BAC084 { get; set; }
        public int? BAC159 { get; set; }
        public int? BAC302 { get; set; }
        public int? BAC303 { get; set; }
        public int? BAC401 { get; set; }
        public int? BAC403 { get; set; }
        public int? BAC501 { get; set; }
        public int? BAC502 { get; set; }
        public int? BAC503 { get; set; }
        public int? BAC550 { get; set; }
        public int? BAC584 { get; set; }
        public int? BAC589 { get; set; }
        public int? BAC601 { get; set; }
        public int? BAC751 { get; set; }
        public int? BAC752 { get; set; }
        public int? BAC801 { get; set; }
        public int? BAC804 { get; set; }
        public int? BAC901 { get; set; }
        public int? BAC903 { get; set; }
        public int? BAC904 { get; set; }
        public int? BAC905 { get; set; }
        public int? BAC906 { get; set; }
        public int? BAC908 { get; set; }
        public int? BNK001 { get; set; }
        public int? BNK026 { get; set; }
        public int? BRR026 { get; set; }
        
        #endregion

        public int? CAP026 { get; set; }
        public int? CAP801 { get; set; }
        public int? CRU001 { get; set; }
        public int? FIL001 { get; set; }
        public int? FIL022 { get; set; }
        public int? FIL023 { get; set; }
        public int? FIN001 { get; set; }
        public int? FIN026 { get; set; }
        public int? FIN601 { get; set; }
        public int? FIN801 { get; set; }

        public int? GBL007 { get; set; }
        public int? HEQ001 { get; set; }
        
        #region ILN
        public int? ILN001 { get; set; }
        public int? ILN002 { get; set; }
        public int? ILN005 { get; set; }
        public int? ILN006 { get; set; }
        public int? ILN007 { get; set; }
        public int? ILN022 { get; set; }
        public int? ILN023 { get; set; }
        public int? ILN026 { get; set; }
        public int? ILN064 { get; set; }
        public int? ILN067 { get; set; }
        public int? ILN071 { get; set; }
        public int? ILN074 { get; set; }
        public int? ILN075 { get; set; }
        public int? ILN076 { get; set; }
        public int? ILN077 { get; set; }
        public int? ILN078 { get; set; }
        public int? ILN080 { get; set; }
        public int? ILN081 { get; set; }
        public int? ILN084 { get; set; }
        public int? ILN085 { get; set; }
        public int? ILN086 { get; set; }
        public int? ILN101 { get; set; }
        public int? ILN102 { get; set; }
        public int? ILN103 { get; set; }
        public int? ILN104 { get; set; }
        public int? ILN105 { get; set; }
        public int? ILN106 { get; set; }
        public int? ILN107 { get; set; }
        public int? ILN108 { get; set; }
        public int? ILN109 { get; set; }
        public int? ILN110 { get; set; }
        public int? ILN111 { get; set; }
        public int? ILN112 { get; set; }
        public int? ILN113 { get; set; }
        public int? ILN114 { get; set; }
        public int? ILN115 { get; set; }
        public int? ILN116 { get; set; }
        public int? ILN117 { get; set; }
        public int? ILN118 { get; set; }
        public int? ILN119 { get; set; }
        public int? ILN122 { get; set; }
        public int? ILN124 { get; set; }
        public int? ILN125 { get; set; }
        public int? ILN126 { get; set; }
        public int? ILN127 { get; set; }
        public int? ILN128 { get; set; }
        public int? ILN129 { get; set; }
        public int? ILN130 { get; set; }
        public int? ILN201 { get; set; }
        public int? ILN301 { get; set; }
        public int? ILN302 { get; set; }
        public int? ILN403 { get; set; }
        public int? ILN501 { get; set; }
        public int? ILN502 { get; set; }
        public int? ILN503 { get; set; }
        public int? ILN504 { get; set; }
        public int? ILN601 { get; set; }
        public int? ILN701 { get; set; }
        public int? ILN702 { get; set; }
        public int? ILN703 { get; set; }
        public int? ILN720 { get; set; }
        public int? ILN724 { get; set; }
        public int? ILN740 { get; set; }
        public int? ILN801 { get; set; }
        public int? ILN804 { get; set; }
        public int? ILN901 { get; set; }
        public int? ILN903 { get; set; }
        public int? ILN904 { get; set; }
        public int? ILN905 { get; set; }
        public int? ILN906 { get; set; }
        public int? ILN908 { get; set; }
        public int? ILN914 { get; set; }
        #endregion
        public int? LFI801 { get; set; }
        
        #region REF
        public int? REF001 { get; set; }
        #endregion

        #region REP
        public int? REP001 { get; set; }
        public int? REP002 { get; set; }
        public int? REP005 { get; set; }
        public int? REP026 { get; set; }
        public int? REP071 { get; set; }
        public int? REP074 { get; set; }
        public int? REP075 { get; set; }
        public int? REP076 { get; set; }
        public int? REP077 { get; set; }
        public int? REP078 { get; set; }
        public int? REP080 { get; set; }
        public int? REP081 { get; set; }
        public int? REP084 { get; set; }
        public int? REP302 { get; set; }
        public int? REP501 { get; set; }
        public int? REP503 { get; set; }
        public int? REP601 { get; set; }
        public int? REP901 { get; set; }
        public int? REP903 { get; set; }
        public int? REP904 { get; set; }
        public int? REP905 { get; set; }
        public int? REP906 { get; set; }
        public int? REP908 { get; set; }
        #endregion

        #region REV
        public int? REV001 { get; set; }
        public int? REV002 { get; set; }
        public int? REV005 { get; set; }
        public int? REV006 { get; set; }
        public int? REV007 { get; set; }
        public int? REV022 { get; set; }
        public int? REV023 { get; set; }
        public int? REV024 { get; set; }
        public int? REV026 { get; set; }
        public int? REV028 { get; set; }
        public int? REV038 { get; set; }
        public int? REV044 { get; set; }
        public int? REV064 { get; set; }
        public int? REV067 { get; set; }
        public int? REV071 { get; set; }
        public int? REV074 { get; set; }
        public int? REV075 { get; set; }
        public int? REV076 { get; set; }
        public int? REV077 { get; set; }
        public int? REV078 { get; set; }
        public int? REV080 { get; set; }
        public int? REV081 { get; set; }
        public int? REV084 { get; set; }
        public int? REV085 { get; set; }
        public int? REV086 { get; set; }
        public int? REV101 { get; set; }
        public int? REV102 { get; set; }
        public int? REV103 { get; set; }
        public int? REV104 { get; set; }
        public int? REV105 { get; set; }
        public int? REV106 { get; set; }
        public int? REV107 { get; set; }
        public int? REV108 { get; set; }
        public int? REV109 { get; set; }
        public int? REV110 { get; set; }
        public int? REV111 { get; set; }
        public int? REV112 { get; set; }
        public int? REV113 { get; set; }
        public int? REV114 { get; set; }
        public int? REV115 { get; set; }
        public int? REV116 { get; set; }
        public int? REV117 { get; set; }
        public int? REV118 { get; set; }
        public int? REV119 { get; set; }
        public int? REV122 { get; set; }
        public int? REV124 { get; set; }
        public int? REV125 { get; set; }
        public int? REV126 { get; set; }
        public int? REV127 { get; set; }
        public int? REV128 { get; set; }
        public int? REV129 { get; set; }
        public int? REV130 { get; set; }
        public int? REV159 { get; set; }
        public int? REV201 { get; set; }
        public int? REV202 { get; set; }
        public int? REV301 { get; set; }
        public int? REV302 { get; set; }
        public int? REV401 { get; set; }
        public int? REV403 { get; set; }
        public int? REV404 { get; set; }
        public int? REV501 { get; set; }
        public int? REV502 { get; set; }
        public int? REV503 { get; set; }
        public int? REV504 { get; set; }
        public int? REV524 { get; set; }
        public int? REV550 { get; set; }
        public int? REV584 { get; set; }
        public int? REV585 { get; set; }
        public int? REV589 { get; set; }
        public int? REV590 { get; set; }
        public int? REV601 { get; set; }
        public int? REV701 { get; set; }
        public int? REV702 { get; set; }
        public int? REV703 { get; set; }
        public int? REV720 { get; set; }
        public int? REV724 { get; set; }
        public int? REV740 { get; set; }
        public int? REV751 { get; set; }
        public int? REV752 { get; set; }
        public int? REV901 { get; set; }
        public int? REV903 { get; set; }
        public int? REV904 { get; set; }
        public int? REV905 { get; set; }
        public int? REV906 { get; set; }
        public int? REV908 { get; set; }
        #endregion

        #region RTI
        public int? RTI026 { get; set; }
        #endregion

        #region RTL
        public int? RTL001 { get; set; }
        public int? RTL002 { get; set; }
        public int? RTL005 { get; set; }
        public int? RTL026 { get; set; }
        public int? RTL071 { get; set; }
        public int? RTL074 { get; set; }
        public int? RTL075 { get; set; }
        public int? RTL076 { get; set; }
        public int? RTL077 { get; set; }
        public int? RTL078 { get; set; }
        public int? RTL080 { get; set; }
        public int? RTL081 { get; set; }
        public int? RTL084 { get; set; }
        public int? RTL501 { get; set; }
        public int? RTL502 { get; set; }
        public int? RTL503 { get; set; }
        public int? RTL901 { get; set; }
        public int? RTL903 { get; set; }
        public int? RTL904 { get; set; }
        public int? RTL905 { get; set; }
        public int? RTL906 { get; set; }
        public int? RTL908 { get; set; }
        
        #endregion

        #region RTR
        public int? RTR001 { get; set; }
        public int? RTR002 { get; set; }
        public int? RTR005 { get; set; }
        public int? RTR007 { get; set; }
        public int? RTR022 { get; set; }
        public int? RTR023 { get; set; }
        public int? RTR026 { get; set; }
        public int? RTR028 { get; set; }
        public int? RTR031 { get; set; }
        public int? RTR035 { get; set; }
        public int? RTR044 { get; set; }
        public int? RTR071 { get; set; }
        public int? RTR074 { get; set; }
        public int? RTR075 { get; set; }
        public int? RTR076 { get; set; }
        public int? RTR077 { get; set; }
        public int? RTR078 { get; set; }
        public int? RTR080 { get; set; }
        public int? RTR081 { get; set; }
        public int? RTR084 { get; set; }
        public int? RTR159 { get; set; }
        public int? RTR303 { get; set; }
        public int? RTR401 { get; set; }
        public int? RTR403 { get; set; }
        public int? RTR501 { get; set; }
        public int? RTR584 { get; set; }
        public int? RTR585 { get; set; }
        public int? RTR589 { get; set; }
        public int? RTR590 { get; set; }
        public int? RTR601 { get; set; }
        public int? RTR751 { get; set; }
        public int? RTR752 { get; set; }
        public int? RTR901 { get; set; }
        public int? RTR903 { get; set; }
        public int? RTR904 { get; set; }
        public int? RTR905 { get; set; }
        public int? RTR906 { get; set; }
        public int? RTR908 { get; set; }
#endregion

        #endregion

        public decimal? AmountDelinquent { get; set; }
        public decimal? AmountParticipation { get; set; }
        public decimal? AmountRemaining { get; set; }
        public decimal? BankcardUtilization { get; set; }
        public decimal? BorrowerAPR { get; set; }
        public string BorrowerCity { get; set; }
        public string BorrowerListingDescription { get; set; }
        public string BorrowerMetropolitanArea { get; set; }
        public decimal? BorrowerRate { get; set; }
        public string BorrowerState { get; set; }
        public int? ChannelCode { get; set; }
        public int? CreditLinesLast7Years { get; set; }
        public DateTime? CreditPullDate { get; set; }
        public int? CurrentCreditLines { get; set; }
        public int? CurrentDelinquencies { get; set; }
        public decimal? DTIwProsperLoan { get; set; }
        public int? DelinquenciesLast7Years { get; set; }
        public int? DelinquenciesOver30Days { get; set; }
        public int? DelinquenciesOver60Days { get; set; }
        public int? DelinquenciesOver90Days { get; set; }
        public Decimal? EffectiveYield { get; set; }
        public string EmploymentStatusDescription { get; set; }
        public decimal? EstimatedLossRate { get; set; }
        public decimal? EstimatedReturn { get; set; }
        public string FICOScore { get; set; }
        public DateTime? FirstRecordedCreditLine { get; set; }
        public decimal? FundingThreshold { get; set; }
        public bool? GroupIndicator { get; set; }
        public string GroupName  { get; set; }
        public int IncomeRange { get; set; }
        public string IncomeRangeDescription { get; set; }
        public bool? IncomeVerifiable { get; set; }
        public int? InquiriesLast6Months { get; set; }
        public decimal? InstallmentBalance { get; set; }
        public string InvestmentTypeDescription { get; set; }
        public int? InvestmentTypeID { get; set; }
        public bool? IsHomeowner { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public int? LenderIndicator { get; set; }
        public decimal? LenderYield { get; set; }
        public decimal? ListingAmountFunded { get; set; }
        public int? ListingCategory { get; set; }
        public DateTime? ListingCreationDate { get; set; }
        public DateTime? ListingEndDate  { get; set; }
        public decimal? ListingMonthlyPayment { get; set; }
        public int? ListingNumber { get; set; }
        public int? ListingPurpose  { get; set; }
        public Decimal? ListingRequestAmount { get; set; }
        public DateTime? ListingStartDate { get; set; }
        public int? ListingStatus { get; set; }
        public string ListingStatusDescription { get; set; }
        public int? ListingTerm { get; set; }
        public string ListingTitle { get; set; }
        public int? LoanNumber  { get; set; }
        public DateTime? LoanOriginationDate  { get; set; }
        public decimal? MaxPriorProsperLoan  { get; set; }
        public string MemberKey { get; set; }
        public decimal? MinPriorProsperLoan  { get; set; }
        public decimal? MonthlyDebt { get; set; }
        public int? MonthsEmployed { get; set; }
        public int? NowDelinquentDerog { get; set; }
        public string Occupation { get; set; }
        public string OldestTradeOpenDate { get; set; }
        public int? OpenCreditLines { get; set; }
        public bool? PartialFundingIndicator { get; set; }
        public decimal? PercentFunded { get; set; }
        public string PriorProsperLoanEarliestPayOff  { get; set; }
        public int? PriorProsperLoans { get; set; }
        public int? PriorProsperLoans31DPD  { get; set; }
        public int? PriorProsperLoans61DPD  { get; set; }
        public int? PriorProsperLoansActive { get; set; }
        public decimal? PriorProsperLoansBalanceOutstanding  { get; set; }
        public int? PriorProsperLoansCyclesBilled  { get; set; }
        public int? PriorProsperLoansLateCycles  { get; set; }
        public int? PriorProsperLoansLatePaymentsOneMonthPlus  { get; set; }
        public int? PriorProsperLoansOnTimePayments { get; set; }
        public decimal? PriorProsperLoansPrincipalBorrowed { get; set; }
        public decimal? PriorProsperLoansPrincipalOutstanding { get; set; }
        public string ProsperRating { get; set; }
        public int? ProsperScore { get; set; }
        public int? PublicRecordsLast10Years { get; set; }
        public int? PublicRecordsLast12Months { get; set; }
        public decimal? RealEstateBalance { get; set; }
        public decimal? RealEstatePayment { get; set; }
        public decimal? RevolvingAvailablePercent { get; set; }
        public decimal? RevolvingBalance { get; set; }
        public int? SatisfactoryAccounts { get; set; }
        public string ScoreX { get; set; }
        public string ScoreXChange { get; set; }
        public decimal? StatedMonthlyIncome { get; set; }
        public int? TotalInquiries { get; set; }
        public int? TotalOpenRevolvingAccounts { get; set; }
        public int? TotalTradeItems { get; set; }
        public int? VerificationStage { get; set; }
        public int? WasDelinquentDerog { get; set; }
        public DateTime? WholeLoanEndDate { get; set; }
        public DateTime? WholeLoanStartDate { get; set; }

    }
}
